site_name: Innmind/BlackBox
repo_name: Innmind/BlackBox
docs_dir: documentation

nav:
  - Home: index.md
  - Preface:
    - Philosophy: preface/philosophy.md
    - Terminology: preface/terminology.md
  - First steps:
    - Writing your first test with BlackBox: test.md
    - Discovering Sets: sets.md
    - Writing your first proof: proof.md
    - Writing your first property: property.md
    - Organize your proofs: organize.md
    - Using tags: tags.md
    - Configuring the test runner: config.md
    - Asserting memory usage: assert_memory.md
    - Adding assertions: own_assertions.md
    - Compatibility with PHPUnit: phpunit.md
  - Internals:
    - internals/index.md
    - Shrinking: internals/shrinking.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font: false
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue
      accent: deep orange
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: deep orange
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - abbr
  - admonition
  - pymdownx.details:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - privacy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Innmind/BlackBox
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/Baptouuuu
