name: CI

on: [push, pull_request]

jobs:
  phpunit_latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4', '8.0']
        dependency-versions: ['lowest', 'highest']
    name: 'PHPUnit Latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
      - name: Composer
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: PHPUnit
        run: vendor/bin/phpunit --fail-on-risky --coverage-clover=coverage.clover --exclude-group failing-on-purpose
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  phpunit_old:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4', '8.0']
        phpunit-version: ['8']
    name: 'PHPUnit'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
      - name: Composer
        uses: "ramsey/composer-install@v2"
      - name: Install PHPUnit ${{ matrix.phpunit-version }}
        run: composer remove phpunit/phpunit && composer require sebastian/diff '~3.0' && composer require phpunit/phpunit '~${{ matrix.phpunit-version }}.0'
      - name: PHPUnit
        run: vendor/bin/phpunit -c phpunit-${{ matrix.phpunit-version }}.xml.dist --fail-on-risky --coverage-clover=coverage.clover --exclude-group failing-on-purpose,only-latest
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  phpunit_printer_class_latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4', '8.0']
        detailed-properties: [1, 0]
    name: 'PHPUnit Printer Class Latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Composer
        uses: "ramsey/composer-install@v2"
      - name: PHPUnit Printer Class
        run: |
          set +e
          vendor/bin/phpunit --group failing-on-purpose
          if [[ $? -eq 0 ]]; then exit 1; else exit 0; fi
        env:
          BLACKBOX_DETAILED_PROPERTIES: ${{ matrix.detailed-properties }}
  phpunit_printer_class_old:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4', '8.0']
        phpunit-version: ['8']
        detailed-properties: [1, 0]
    name: 'PHPUnit Printer Class'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
          coverage: none
      - name: Composer
        uses: "ramsey/composer-install@v2"
      - name: Install PHPUnit ${{ matrix.phpunit-version }}
        run: composer remove phpunit/phpunit && composer require sebastian/diff '~3.0' && composer require phpunit/phpunit '~${{ matrix.phpunit-version }}.0'
      - name: PHPUnit Printer Class
        run: |
          set +e
          vendor/bin/phpunit -c phpunit-${{ matrix.phpunit-version }}.xml.dist --group failing-on-purpose --exclude-group only-latest
          if [[ $? -eq 0 ]]; then exit 1; else exit 0; fi
        env:
          BLACKBOX_DETAILED_PROPERTIES: ${{ matrix.detailed-properties }}
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
    name: 'Psalm'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Composer
        uses: "ramsey/composer-install@v2"
      - name: Psalm
        run: vendor/bin/psalm --shepherd
  cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']
    name: 'CS'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl
      - name: Composer
        uses: "ramsey/composer-install@v2"
      - name: CS
        run: vendor/bin/php-cs-fixer fix --diff --dry-run --diff-format udiff
